on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            artifact_name: rsendmail
            asset_name: rsendmail-linux-gnu-x86_64-${{ github.ref }}.zip
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: rsendmail.exe
            asset_name: rsendmail-windows-x86_64-${{ github.ref }}.zip
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            artifact_name: rsendmail
            asset_name: rsendmail-darwin-x86_64-${{ github.ref }}.zip
            command: both

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            artifact_name: rsendmail
            asset_name: rsendmail-darwin-aarch64-${{ github.ref }}.zip
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Cache
        uses: Swatinem/rust-cache@v2
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
          GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.asset_name }}
          path: target/release/${{ matrix.platform.artifact_name }}
